### ISSUE TITLE
Player icons are corrupted and project is not usable.

### ISSUE THREAD

**Issue by JBRPG** [GeneralProtectionFault/InputLocalMultiplayerTemplate#2]
Opened up the project and one problem is the UnityShim, which does not exist anywhere in the project.

Also, player cursor icons are corrupted. Therefore, I cannot use the project to experiment.

**Comment by GeneralProtectionFault** [comment]
The UnityShim error seems to be an error related to the Github for Unity plugin.  It hasn't been maintained, so I removed it (just using Visual Studio instead).  I also uploaded overwrites of the cursor icons, so hopefully that's fixed.  Also, you can substitute your own images there if you wish.
